project:
  type: website
  output-dir: docs

website:
  title: "webpyramid"
  navbar:
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/webplusangels
      - icon: instagram
        href: https://instagram.com/nimwver
format:
  html:
    theme: cosmo
    css: styles.css



